version: '3.3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - '3001:3000'

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
      