version: '3.3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '5000:3000'
    depends_on:
      - router
    restart: always  

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - '5001:3000'
    depends_on:
      - router
    restart: always  

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - '5002:3000'
    depends_on:
      - router
    restart: always  
  
  forms:
    build:
      context: ./forms
      dockerfile: Dockerfile
    ports:
      - '5003:3000'
    depends_on:
      - router
    restart: always

  router:
    build:
      context: ./router
      dockerfile: Dockerfile
    ports:
      - '8080:8000'
    restart: always
